apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp
  namespace: demo
  labels:
    app: weatherapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp
        image: agus3rdyoga/weather-app
        ports:
        - name: http
          containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
